### ISSUE TITLE
可否再帮忙修改下关于三字和四字以上的转换判断逻辑呢

### ISSUE THREAD

**Issue by Bravo911** [Oyami-Srk/Squirrel-workflow#3]
目前的设置，你将三字和四字以上的转换和平常的二字完全隔离了，可以转三字和四字以上的时候是无法转二字的，反之也是，这个判断逻辑就没那么人性化。

我每次都要进去修改就痛苦了。

所以希望你能不能改变下，打开开关的时候，二三四字都可以进行转换，关闭的时候，就二字可以转化，或者是二三四字按照你之前的那个逻辑来进行转化。

这个开关的意义就是为那些不需要我这套三四字转换逻辑的人使用。

大家其乐融融多好呢，对吧。

**Comment by Oyami-Srk** [comment]
这是个Bug XD我少写了一行代码，现在已经解决了。
