### ISSUE TITLE
1.3版如何开启三和四字以上的转码

### ISSUE THREAD

**Issue by Bravo911** [Oyami-Srk/Squirrel-workflow#5]
大哥，饶恕小弟的愚昧，真的找不到如何打开转换啊！

**Comment by Oyami-Srk** [comment]
首先打开Alfred Preferences，然后在Workflows中点击Rime。
随后会出现工作流的流程图，然后在流程图的那个深色区域的右上角，有四个按钮。
其中第二个是“【x】”状。点击这第二个按钮，双击右侧`IsReformatting`后面的False，使其成为可编辑状态，输入True，并点击右下角的Save，将其保存。
注意一定要输入True，大小写敏感。

**Comment by Bravo911** [comment]
太酷了，建议增加相关说明，说不定以后就不是我们两个人在用了呢。现在是完美版。

**Comment by Oyami-Srk** [comment]
已经添加说明到Readme，谢谢~
